site_name: Personal Domains Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Budget: budget.md
  - Investing: investing.md
  - Personal Assets: personal-assets.md
  - Goals: goals.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list